use data_analyst_project;
select * from customer_behavior_analysis;

-- 1.which category generates highest revenue?-
select category,
round(sum(purchase_amount),2) as highest_revenue
from customer_behavior_analysis 
group by category
order by highest_revenue desc;

-- Are discounts actually increase purchase values?
select discount_applied,
round(sum(purchase_amount),2) as increase_revenue
from customer_behavior_analysis
 group by discount_applied
order by increase_revenue desc;

-- what  is the total revenue generated by male and female customer.
select gender,
round(sum(purchase_amount),2)as Total_revenue
from customer_behavior_analysis
group by gender
order by total_revenue desc;

-- which customer used a discount but still spent more than average purchase amount.
select customer_id,discount_applied,purchase_amount 
from customer_behavior_analysis
where  discount_applied='Yes' and purchase_amount> (select avg(purchase_amount) from customer_behavior_analysis)
order by purchase_amount desc
limit 10;

-- which are the top/bottom 5 products with the heighest average review rating.
select item_purchased,round(avg(review_rating),2) as heighest_avg_review_rating
from customer_behavior_analysis
group by item_purchased
order by heighest_avg_review_rating desc
limit 5;

-- Avearage purchashed :- standard vs express shipping
select shipping_type,count(customer_id)as total_order
,round(avg(purchase_amount),2) as avg_purchase
from customer_behavior_analysis
where shipping_type in("standard","Express")
 group by shipping_type ;
 
 -- compare average spend vs total Revenue  b/w suscribers and non suscribers.
 select * from customer_behavior_analysis;
 
 select subscription_status,
 count(customer_id),
 round(avg(purchase_amount),2) as avg_spend ,
 round(sum(purchase_amount),2)as total_revenue
 from customer_behavior_analysis
 group by  subscription_status
 order by total_revenue desc;
 
 -- Top 5 products highest discount usage %.
 select * from customer_behavior_analysis;
 
 select item_purchased,count(item_purchased) as Total_orders,
 sum(
 case
 when discount_applied='Yes' Then 1
 else 0
 end
 ) as total_discount,
 round(sum(
 case
 when discount_applied='Yes' Then 1
 else 0
 end
 )*100/count(*),2)as discount_usage_percent
from customer_behavior_analysis
 group by item_purchased
 order by  discount_usage_percent desc
 limit 5;
 
 -- Customer Segmentation: New, Returning, Loyal Customers
 
  select * from customer_behavior_analysis;
  select customer_id, count(*)as total_purchased,
  Case
  when count(*) =1 then "New Customer"
   when count(*) between 2 and 8 then  "Returning"
   else "Loyal ciustomers"
   end as customer_segement
   from customer_behavior_analysis
   group by customer_id;
   
  -- --9. What are the top 3 most purchased products within each category ?
    select * from customer_behavior_analysis;
WITH CTE AS 
(
select 
	category,
	item_purchased,
	COUNT(item_purchased) AS most_purchased,
	dense_rank() OVER (PARTITION BY category ORDER BY COUNT(item_purchased) DESC) AS RNK
FROM customer_behavior_analysis
GROUP BY category,item_purchased
)
SELECT * FROM CTE
WHERE RNK <=3;

-- 12. What is the revenue contribution of each age group ? 
  select * from customer_behavior_analysis;
  select
  case 
  when age between 18 and 25 then '18-25'
  when age between 26 and 35 then '26-35'
  when age between 35 and 50 then '35-50'
  else '51+'
  end as age_group,
  round(sum(purchase_amount),2) as Total_revenue
  from customer_behavior_analysis
  group by  case 
  when age between 18 and 25 then '18-25'
  when age between 26 and 35 then '26-35'
  when age between 35 and 50 then '35-50'
  else '51+'
  end
  order by Total_revenue desc;